### ISSUE TITLE
Source code folder structure

### ISSUE THREAD

**Issue by ripa1995** [runtime-machines/react-template#5]
## Motivations

- Would you like to implement this feature? [y/n] N

## Solution

Give a predefined structure that files inside `src` should follow. I was thinking something like this one: https://www.xenonstack.com/insights/reactjs-project-structure which looks really good to me. 
Also, in the `README.MD` add a small description of each folder, as it is described in the website linked.

**Comment by Eliaxie** [comment]
added src structure and improved readme c53662806f5b8f08000ec427783e28caff8428c0
